### ISSUE TITLE
Start all comments with a space to make it easier to read.

### ISSUE THREAD

**Issue by asial-matagawa** [DomSas/Restaurant-Management-App#24]
@DomSas @pmateosga (Cc: @yong-asial)

Related:
- #23 

----

## Suggestion

From Airbnb Style Guide:

> [18.3](https://github.com/airbnb/javascript#comments--spaces) Start all comments with a space to make it easier to read. eslint: [spaced-comment](https://eslint.org/docs/rules/spaced-comment)
> 
> ```js
> // bad
> //is current tab
> const active = true;
> ```
> 
> ```js
> // good
> // is current tab
> const active = true;
> 
> ```
> ```js
> // bad
> /**
>  *make() returns a new element
>  *based on the passed-in tag name
>  */
> function make(tag) {
> 
>   // ...
> 
>   return element;
> }
> ```
> 
> ```js
> // good
> /**
>  * make() returns a new element
>  * based on the passed-in tag name
>  */
> function make(tag) {
> 
>   // ...
> 
>   return element;
> }
> ```

**Comment by asial-matagawa** [comment]
@pmateosga 
It seems that `https://` and `http://` were also affected and replaced with `https:// ` and `http:// `. Could you fix them?

**Comment by pablomatgar** [comment]
@asial-matagawa Dominik and I have just realised that. We have already fixed it and push it soon :)

**Comment by asial-matagawa** [comment]
@pmateosga 
Great! Thank you :+1:
