### ISSUE TITLE
Preview is not working on cloud IDE

### ISSUE THREAD

**Issue by yong-asial** [DomSas/Restaurant-Management-App#38]
![Screen Shot 2022-02-08 at 21 43 53](https://user-images.githubusercontent.com/28589278/152989550-26ae412a-0527-4376-baa2-d5f2c4a93ade.png)

It might due to you are using ` NODE_ENV=development` twice in both `dev` and `build-prod`

Note: on Cloud IDE, it is running `monaca preview` which run `monaca:preview`

**Comment by yong-asial** [comment]
@DomSas please try this PR - https://github.com/DomSas/Restaurant-Management-App/pull/47

I think the main fix is to downgrade the webpack-dev-server to version 3.x. Maybe the webpack-dev-server 4.x requires stricter rules.

**Comment by DomSas** [comment]
Thank you @yong-asial , PR #47 solved it so I am closing this issue.
